# =============================================================
# FILE: src/utils/export.py
# PURPOSE: Export contract analysis results as text report
#
# WHAT THIS DOES:
# After analyzing a contract, users can export the full
# analysis as a clean text report they can save or share.
# =============================================================

from datetime import datetime
from typing import Dict


def generate_text_report(
    contract_name: str,
    risk_result: Dict,
    qa_results: list = None
) -> str:
    """
    WHAT THIS DOES:
    Generates a clean plain text report of the contract analysis.
    
    INPUT:
        contract_name → name of the analyzed contract
        risk_result   → risk scoring results dictionary
        qa_results    → list of Q&A results (optional)
    
    OUTPUT:
        Formatted text report as string
    """

    report = f"""
================================================================================
                        LEXIQUERY CONTRACT ANALYSIS REPORT
================================================================================

Contract:     {contract_name}
Generated:    {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Analyzed by:  LexiQuery — AI-Powered Legal Contract Analyzer

================================================================================
                              RISK ASSESSMENT
================================================================================

Risk Score:   {risk_result.get('risk_score', 'N/A')}/10
Risk Level:   {risk_result.get('risk_level', 'N/A')}

Summary:
{risk_result.get('summary', 'No summary available')}

--------------------------------------------------------------------------------
Red Flags:
"""

    red_flags = risk_result.get('red_flags', [])
    if red_flags:
        for flag in red_flags:
            if flag.strip():
                report += f"  • {flag}\n"
    else:
        report += "  • No significant red flags identified\n"

    report += """
--------------------------------------------------------------------------------
Recommendations:
"""

    recommendations = risk_result.get('recommendations', [])
    if recommendations:
        for rec in recommendations:
            if rec.strip():
                report += f"  • {rec}\n"
    else:
        report += "  • No specific recommendations\n"

    if qa_results:
        report += """
================================================================================
                              Q&A ANALYSIS
================================================================================
"""
        for qa in qa_results:
            report += f"""
Question: {qa.get('question', '')}
Answer:   {qa.get('answer', '')}
Sources:  {', '.join(qa.get('sources', []))}
--------------------------------------------------------------------------------
"""

    report += f"""
================================================================================
DISCLAIMER: This report is generated by AI and is for informational purposes 
only. It does not constitute legal advice. Always consult a qualified lawyer 
for important legal decisions.
================================================================================
Generated by LexiQuery | Built by Ronil Muchandi | MS Data Science, Mizzou
================================================================================
"""

    return report


def save_report(report_text: str, filename: str = None) -> str:
    """
    WHAT THIS DOES:
    Saves the report to the outputs folder.
    
    INPUT:
        report_text → the report content
        filename    → optional custom filename
    
    OUTPUT:
        Path to saved file
    """
    if not filename:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"analysis_{timestamp}.txt"

    output_path = f"data/outputs/{filename}"

    with open(output_path, 'w') as f:
        f.write(report_text)

    return output_path